Traceback (most recent call last):
  File "/home/lnsx/projects/testovoe/backend/main.py", line 20, in <module>
    app.listen(8888)
  File "/home/lnsx/projects/testovoe/backend/.venv/lib/python3.9/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/home/lnsx/projects/testovoe/backend/.venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/lnsx/projects/testovoe/backend/.venv/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/lnsx/projects/testovoe/backend/main.py", line 21, in <module>
    tornado.ioloop.IOLoop.current().start()
  File "/home/lnsx/projects/testovoe/backend/.venv/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
